spring:
  application:
    name: personal-finance-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/personal_finance_manager
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # options: create, update, validate, none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
